#language: c

sudo: required
dist: trusty

notifications:
  email: false

before_script:
  - sudo apt-get update
  - python3 --version
  - python2 --version
  - "sudo apt-get install -qq python-tk scons git || true"
  - "sudo pip install tensorflow keras matplotlib scikit-learn || true"
  - "pip list"

script:
  - export PYTHONPATH=`pwd`/scripts
  - echo ====== New auto-test ======
  - cd examples/auto_test && python main.py -
  #- mkdir -p examples/mnist-densenet/tmp
  #- echo ====== local NNOM test ======
  #- cd examples/mnist-densenet && python model/mnist_densenet.py && cp -v weights.h mcu && scons && NNOM_TEST_ON_CI=YES python model/mnist_densenet.py && cd -
  #- echo ====== CMSIS NN NNOM test ======
  #- cd examples/mnist-densenet && USE_CMSIS_NN=YES scons && NNOM_TEST_ON_CI=YES python model/mnist_densenet.py && cd -

env:
- NNOM_ON_CI=YES
